server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/ts
    driver-class-name: org.mariadb.jdbc.Driver
    username: test
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: ts
  servlet:
    multipart:
      max-file-size: 10MB

jwt:
  name: Authorization
  expired: 7200000
  token: 123456
  prefix: Bearer

message:
  path: C:\\Users\\m1861\\UserData\\tempFile\\
  acceptExt: mp3,m4a,wav,aac

avatar:
  path: C:\\Users\\m1861\\UserData\\tempFile\\avatar\\
  acceptExt: jpg,png,jpeg,webp
